name: Build Python Executable with Tkinter

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka ordered-set
        
    - name: Build with Nuitka (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m nuitka --onefile --windows-disable-console --enable-plugin=tk-inter main.py
        
    - name: Build with Nuitka (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        python -m nuitka --onefile --enable-plugin=tk-inter main.py
        
    - name: Build with Nuitka (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        python -m nuitka --onefile --enable-plugin=tk-inter main.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pandoc-inmemory-gui-${{ matrix.os }}
        path: |
          main.exe
          main.bin
          main
        retention-days: 30
